### ISSUE TITLE
i get error

### ISSUE THREAD

**Issue by Duao20** [EchoHackCmd/Client-Base#2]
says cannot open minhook when starting

**Comment by 12brendon34** [comment]
gotta download some more ram 100% the problem
https://downloadmoreram.com/

**Comment by EchoHackCmd** [comment]
In Visual Studio click on Project (Top Button) -> Manage NuGet Packages -> Browse: MinHook

Once installed go to the project folder and go to

Packages > minhook.1.3.3 > lib > native > lib` and rename `libMinHook-x64-v141-mdd.lib` to `libMinHook.lib

If it says that MinHook is already installed click on “Uninstall” and then install it again 

Or you'll have missing folders which will make it impossible to proceed with the other steps I've provided you with

**Comment by EchoHackCmd** [comment]
Go to 
`Project` (Top Button) -> `Manage NuGet Packages` -> `Browse: MinHook`

Once installed go to the project folder and go to

`Packages > minhook.1.3.3 > lib > native > lib` and rename `libMinHook-x64-v141-mdd.lib` to `libMinHook.lib`

If it says that MinHook is already installed click on `Uninstall` and then click on `Install`

Or you'll have missing folders which will make it impossible to proceed with the other steps I've provided you with

**Comment by EchoHackCmd** [comment]
I'll keep this open so people can see it

**Comment by Gamerclient28921** [comment]
@EchoHackCmd i changed the v140.mmd.lib and that also works

**Comment by EchoHackCmd** [comment]
Awesome
